name: memento
description: A pratical implementation of Memento design pattern. Useful for restore internal state of objects.
version: 1.0.1
repository: https://github.com/jrcodev/Memento

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.14.4
